### ISSUE TITLE
floss how to backward?

### ISSUE THREAD

**Issue by Eurus-Holmes** [zeakey/iccv2019-fmeasure#1]
when I run:
```
loss = fl(output, target)
loss.backward()
```

it occurred error:
`RuntimeError: grad can be implicitly created only for scalar outputs`

**Comment by Eurus-Holmes** [comment]
And if I use `loss.mean().backward()`, I find it seems that couldn't convergent...

**Comment by acdart** [comment]
> And if I use `loss.mean().backward()`, I find it seems that couldn't convergent...

hello，have u figured out how to use it ?

**Comment by zeakey** [comment]
Did you try different learning rates? Generally FLoss requires larger learning rates than cross-entropy loss.

The experiments in our paper were conducted in caffe.
However, @hanqer applied the pytorch version FLoss to other taks and it worked in his practice.

**Comment by acdart** [comment]
> Did you try different learning rates? Generally FLoss requires larger learning rates than cross-entropy loss.
> 
> The experiments in our paper were conducted in caffe.
> However, @Hanqer applied the pytorch version FLoss to other taks and it worked in his practice.

forget to use sigmoid , and it's already worked, thank u very much
